language: python
python:
 - "2.7"
 - "3.6"

matrix:
  include:
    - name: 3.7_bionic
      python: 3.7
      dist: bionic

    - name: 3.8_bionic
      python: 3.8
      dist: bionic

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade .
 
script:  
 - cd tests
 - nosetests -v --with-coverage --cover-package=entrypoint2 .
 
after_success:
 - coveralls
