language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      env: DIST="xenial"

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade .
 
script:  
 - cd tests
 - nosetests -v --with-coverage --cover-package=entrypoint2 coverage
 
after_success:
 - coveralls
